#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Nov 22 19:38:33 2019

@author: chansa
"""

card_deck = [2,4,5,8,1,2]
hand = []

while sum (hand)<= 17:
    hand.append(card_deck.pop())
print(hand)
    