#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Aug 28 22:31:55 2019

@author: chansa
"""

#Finding the sum of n squares of first n numbers

    
    
    
def sumofN(n,nums):

     for i in range(len(nums)):
          minpos = i
          for j in range(len(nums)):
            if nums[j] > nums[minpos]:
                minpos = n*(n+1)*(2*n+1)/6
        
