#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Oct  8 23:38:28 2019

@author: chansa
"""
Customers = (200,700,7000,11000)

platinum = []
Gold =[]
Silver = []

for points in Customers:
    
    if points >= 5000:
        platinum.append()
    elif points >= 1000:
        Gold.append()
    elif points >= 50:
        Silver.append()



